WINCONS = {
    "Hog Rider",
    "Royal Giant",
    "Elite Barbarians",
    "Battle Ram",
    "Ram Rider",
    "Goblin Giant",
    "Giant",
    "Golem",
    "Electro Giant",
    "X-Bow",
    "Mortar",
    "Royal Hogs",
    "Graveyard",
    "Goblin Drill",
    "Miner",
    "Wall Breakers",
    "Rocket",
    "Lightning",
    "Poison",
    "Three Musketeers",
    "Royal Recruits",
    "Mega Knight",
    "P.E.K.K.A."
    "Goblin Barrel",
    "Elixir Golem",
    "Skeleton Barrel",
    "Boss Bandit",
    "Goblinstein",
    "Giant Skeleton"
}